<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;
use App\Models\Valve;

class emailSecret extends Command {
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:emailSecret';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generates a PHP class with some email info.';

    /**
     * Execute the console command.
     */
    public function handle() {
        $filename = 'MailSecret.php';

        $c = "<?php\n";
        $c.= "//\n";
        $c.= "// Generated by console.\n// php artisan app:emailSecret\n";
        $c.= "// " . Carbon::now() . "\n";
        $c.= "//\n";
        $c.= "namespace App\Mailfiles;\n";
        $c.= "//\n";
        $c.= "class MailSecret {\n";
        $c.= "    public static function mailHost() { return '" . Valve::getValue('MAIL_HOST') ."'; }\n";
        $c.= "    public static function pw() { return '" . Valve::getValue('PW') . "'; }\n";
        $c.= "}\n";

        Storage::disk('mailfiles')->put($filename, $c);
        echo('The End');
    }
}