<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

/* These are used for generating language files: */
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;

/* Language Support */
use Illuminate\Support\Facades\App;
use App\UserClasses\BaseLanguage;

class languageFiles extends Command {
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:languageFiles';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generates the language files.';

    /**
     * Execute the console command.
     */
    public function handle() {
        $filename = 'useLanguage.js';
    
        $c = "// Generated by console.\n// php artisan app:languageFiles\n";
        $c.= "// " . Carbon::now() . "\n";
        $c.= "//\n";
        $c.= "export function useLanguage() {\n";
            $c.= "    function language() {\n";
            $c.= "        const lang = []\n";
                $all = BaseLanguage::getAllLanguages();
        for($i=0; $i<count($all); $i++) {
            $c.= "        lang['" . $all[$i] . "'] = JSON.parse('";
            $c.= BaseLanguage::getJson($all[$i]); 
            $c.= "')\n";
        }
        $c.= "        return lang\n";
        $c.= "    }\n";
        $c.= "    return { language }\n";
        $c.= "}\n";
        
        Storage::disk('lang')->put($filename, $c);
        echo('The End');
    }
}